### ISSUE TITLE
JFR results show ~20% memory overhead by OTEL java-agent 

### ISSUE THREAD

**Issue by shantanu-vsbhosale** [breedx-splk/iguanodon#3]
**Use-Case**
We used iguanodon tests, to see the overhead by Open telemetry agent (latest-1.0) on the spring pet clinic app with k6 load. We increased number of users from 5 to 500. (All requests successful).  We tabulated the results as shown in image. It is observed that app instrumented with OTEL agent has **~20%** more memory footprint as looked from the JFR used heap memory metrics.

<img width="892" alt="Screenshot 2021-03-17 at 10 42 41 AM" src="https://user-images.githubusercontent.com/80242052/111418343-917ac980-870d-11eb-800f-2dacc7b5164e.png">

**Question to the community**
Is this behaviour expected ? What are the results you are getting ?

**Comment by shantanu-vsbhosale** [comment]
Note  :- We got Requests per second in above table from changing the **--iterations** flag to **--durations** flag for k6 load in the iguanodon project. The tests were run for fixed duration of 2 minutes. (This can also be included as a feature of iguanodon)

**Comment by breedx-splk** [comment]
Hi @shantanu-vsbhosale.  Thanks for submitting your results...surprised that you even found this little project, but pretty excited that you were able to use it!

These tests are very much a work in progress, and there is still lots to uncover and improve.  I think that your findings are generally similar to what I have seen in the past...but they MUST be taken with a grain of salt.  A few things to consider:

* The tests are not terribly consistent at the moment, due to the large number of variables. Recommend running multiple passes and averaging?
* The spring petclinic app is a pretty contrived MVC app that does pretty small/simple database calls.  In its normal operation, it does not use much memory nor have much computational load.  While 20% might seem like a lot, in such a small app the overhead of tracing/spans is notable (relatively speaking).
* Ideally, the environments where the components run (database, collector, app) would all be isolated so that database operations wouldn't impact the app and vice versa.  This could contribute to or skew the results.

In any case, the intention is to contribute this work back to the community.  It's still very much a work in progress.  Cheers!

**Comment by shantanu-vsbhosale** [comment]
@breedx-splk  thanks for immediate reply. This project is awesome and looking forward to use this tool. I am closing this  as this  is not a issue but fact.
